# Generated by Django 2.1.5 on 2019-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0002_vdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward_Sli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=80)),
                ('awarded_on', models.DateField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
