# Generated by Django 2.1.5 on 2019-02-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0003_reward_sli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals_Sli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('goal_status', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
