# Generated by Django 2.1.5 on 2019-02-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0005_goals_kr_registration_kr_reward_kr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VDP',
        ),
    ]
